source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# Comment out this line if working on cineio-ios
#pod 'cineio-broadcast-ios', '~> 0.7'

# Uncomment this line if working on cineio-ios
pod 'cineio-broadcast-ios', path: '/Users/WilliamShi/Desktop/HoopMediaStreamer/cineio-broadcast-ios'
#pod 'cineio-broadcast-ios', :git => 'https://github.com/HupuInc/cineio-broadcast-ios.git'

# Uncomment this line if working on VideoCore
pod 'VideoCore', path: '/Users/WilliamShi/Desktop/HoopMediaStreamer/VideoCore'
